version: '2'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mensajeria_db1
      MYSQL_USER: david
      MYSQL_PASSWORD: 95070105641
    ports:
      - "3300:3306"
  app:
    build: .
    command: bundle exec rails s -p 3200 -b '0.0.0.0'
    volumes:
      - .:/mensajeria/:rw
    ports:
      - "3200:3200"
    depends_on:
      - db
    links:
      - db
    environment:
      DB_USER: root
      DB_NAME: mensajeria
      DB_PASSWORD: password
      DB_HOST: db